plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.high'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenLocal() // 해당 구문 추가
	mavenCentral()
	maven { url 'https://jitpack.io' }
}

ext {
	set('springCloudVersion', "2025.0.0")
}

dependencies {

    // Logstash Logback Encoder
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'

	// Spring Cloud & Boot Starters
	implementation 'org.springframework.cloud:spring-cloud-starter-config'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'


	// DB & Messaging
	implementation 'com.mysql:mysql-connector-j' // MySQL JDBC Driver
	implementation 'org.springframework.kafka:spring-kafka' // Kafka 의존성

	// Common Modules (Library)
	implementation 'com.github.sharedeffort:common-module:v1.1.9'
	implementation 'com.github.sharedeffort:common-jpa:v1.0.3'

	// Tools
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'com.h2database:h2' // H2 In-memory DB for testing

	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'


}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}