CREATE DATABASE IF NOT EXISTS user_service;
CREATE DATABASE IF NOT EXISTS order_service;
CREATE DATABASE IF NOT EXISTS product_service;
CREATE DATABASE IF NOT EXISTS coupon_service;
CREATE DATABASE IF NOT EXISTS external_service;
CREATE DATABASE IF NOT EXISTS payment_service;