spring:
  application:
    name: external-service
  config:
    import: "optional:configserver:config"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: external-service
    hostname: localhost


slack:
  token: ${SLACK_TOKEN}
