server:
  port: 8700

spring:
  application:
    name: cart-service
  data:
    mongodb:
      # Connection String 사용 (가장 일반적)
      uri: mongodb://admin:admin1234@localhost:27017/msa_mongo_db?authSource=admin

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: cart-service-group

  topic:
    clear-cart: cart-clear-request

logging:
  level:
    com.high.cart: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
  logback:
    rollingpolicy:
      max-file-size: 10MB           # 파일 최대 크기
      max-history: 7                # 7일간 보관
      total-size-cap: 1GB           # 전체 로그 최대 1GB
      clean-history-on-start: true  # 시작 시 오래된 로그 정리