server:
  port: 8900

spring:
  application:
    name: orchestration-service
  datasource:
    url: jdbc:mysql://localhost:3306/orchestration_service?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: orchestration_service
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orchestration-group
      auto-offset-reset: earliest
    listener:
      ack-mode: record
    producer:
      retries: 3
      acks: all

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
  logback:
    rollingpolicy:
      max-file-size: 10MB           # 파일 최대 크기
      max-history: 7                # 7일간 보관
      total-size-cap: 1GB           # 전체 로그 최대 1GB
      clean-history-on-start: true  # 시작 시 오래된 로그 정리

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

