server:
  port: 8200

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: product_service
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data: # 에러 발생하면 이 부분 삭제하기
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms

  cache:
    type: redis
    redis:
      time-to-live: 5000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: product::

redisson:
  mode: single
  single:
    address: redis://localhost:6379
#  mode: cluster # 나중에 K8s로 배포를 한다고 가정하면 필요한 코드
#  cluster:
#    nodes:
#      - redis://redis-0.redis:6379
#      - redis://redis-1.redis:6379
#      - redis://redis-2.redis:6379
  lock:
    wait-time: 5s
    lease-time: 15s

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0