server:
  port: 8300

spring:
  application:
    name: payment-service

  # Config Server 사용
  config:
    import: "optional:configserver:"

  cloud:
    config:
      # config-server는 Eureka로 찾지 않고, URL로 직접 접근
      discovery:
        enabled: false
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, loggers, refresh
  endpoint:
    health:
      show-details: never
    prometheus:
      access: read_only

# 통합 테스트에서는 Eureka도 같이 띄운다고 가정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true     # 통합 테스트면 true로 두는 것이 자연스럽습니다
    fetch-registry: true
  instance:
    instance-id: payment-service
    hostname: localhost

# FeignClient에서 사용하는 user-service URL
user-service:
  url: http://localhost:8081


payment:
  intent:
    ttl-minutes: 15   # PENDING 유지 최대 시간
  scheduler:
    payment-timeout:
      fixed-delay-ms: 60000  # 1분마다 스캔
      batch-size: 200

