input {
  tcp {
    port => 5000
    codec => json_lines
    tags => ["tcp-input"]
  }

  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["msa_app_logs"]
    group_id => "logstash-consumer-group"
    codec => json
    tags => ["kafka-input"]
  }
}

filter {
  if "kafka-input" in [tags] {

    if [service_name] {
      mutate {
        gsub => [ "service_name", "^.*/", "" ]
        gsub => [ "service_name", "-json\.log$", "" ]
      }
    }
    mutate { remove_field => ["service.name", "serviceName"] }

    if [duration_ms] {
      mutate { convert => { "duration_ms" => "integer" } }
    }

    date {
      match => [ "@timestamp", "ISO8601", "yyyy-MM-dd'T'HH:mm:ss.SSSZ" ]
      target => "@timestamp"
      timezone => "Asia/Seoul"
    }

    if [logger_name] =~ /org\.hibernate\.SQL/ {
      mutate { replace => { "log.type" => "sql" } }
    } else if ![log.type] {
      mutate { add_field => { "log.type" => "application" } }
    }

    if [level] {
      mutate {
        strip => ["level"]
        uppercase => ["level"]
      }
    }

    if [level] == "ERROR" and [log.type] == "api_request" {
      clone {
        clones => ["slack_alert"]
      }
    }

    if [type] == "slack_alert" {
      mutate {
        add_field => {
          "targetSlackId" => "C0A3XR53W2K"
          "serviceName" => "%{service_name}"
          "urlPath" => "%{url.path}"
          "timestamp" => "%{@timestamp}"
        }
      }
      mutate {
              remove_field => ["log.type", "@timestamp"]
            }
      prune {
        whitelist_names => ["targetSlackId", "serviceName", "urlPath", "type", "timestamp","message"]
      }
    }
  }
}

output {
  if [type] != "slack_alert" {
    if [level] == "ERROR" {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "msa-errors-%{+YYYY.MM.dd}"
      }
    } else {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "msa-app-logs-%{+YYYY.MM.dd}"
      }
    }
  }

  if [type] == "slack_alert" {
    kafka {
      bootstrap_servers => "kafka:29092"
      topic_id => "alert-slack-topic"
      codec => json
    }
  }
}